title:              Reshape Mind
email:              "ridhisharma@reshapemind.com"
author:             Reshape Mind
baseurl:            "/"
url:                "http://reshapemind.com"
form_id:            "f/xwkwrndk"

# Social Profiles
instagram_username: reshapemind
linkedin_username: reshapemind

collections:
  trainings:
    output: true
  events:
    output: true
  testimonials:
    output: true

# Build settings
markdown:           kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site